name: Deploy
on: [push ,workflow_dispatch]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: getting the code
        uses: actions/checkout@v4
      - name: use node 
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependency
        run: npm ci
      - name: test
        run: npm test
  deploy:
    
    runs-on: ubuntu-latest
    steps:
      - name: getting the code
        uses: actions/checkout@v4
      - name: use node 
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependency
        run: npm ci
      - name: deploing
        run: echo "Deploying ...."

  
