name: Event Demo 1
on: 
 push:
  branches:
    - main
    
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{toJson(github.event)}}"
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install dependancy
        run: npm ci
      - name: Test code
        run: npm run test
  build:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependancy
        run: npm ci
      - name: Building website
        run:  npm run build
  deplo:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying...."

   



  